-- Supabase setup for ELINE Parapharmacie
-- 1. Crée les tables (products, orders, order_items)
-- 2. Active RLS et crée les politiques d'accès public
-- 3. Insère 32 produits de démonstration
--
-- Exécute CE FICHIER EN ENTIER dans le SQL Editor de Supabase.

-- ═══════════════════════════════════════════
-- SCHEMA
-- ═══════════════════════════════════════════

create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price numeric(10, 3) not null check (price >= 0),
  category text not null,
  category_public text,
  subcategory text,
  image_url text,
  discount_percent numeric(5, 2) check (
    discount_percent is null
    or (discount_percent >= 0 and discount_percent <= 100)
  ),
  created_at timestamptz default now() not null
);

create table if not exists orders (
  id uuid default gen_random_uuid() primary key,
  customer_name text not null,
  customer_email text not null,
  customer_phone text not null,
  customer_address text not null,
  total_amount numeric(10, 3) not null check (total_amount >= 0),
  status text default 'pending' not null,
  created_at timestamptz default now() not null
);

create table if not exists order_items (
  id bigint generated by default as identity primary key,
  order_id uuid references orders(id) on delete cascade not null,
  product_id bigint references products(id) on delete set null,
  quantity integer not null check (quantity > 0),
  price numeric(10, 3) not null check (price >= 0),
  created_at timestamptz default now() not null
);

alter table products enable row level security;
alter table orders enable row level security;
alter table order_items enable row level security;

drop policy if exists "products_select_public" on products;
drop policy if exists "products_insert_public" on products;
drop policy if exists "products_update_public" on products;
drop policy if exists "products_delete_public" on products;

create policy "products_select_public"
on products for select
using (true);

create policy "products_insert_public"
on products for insert
with check (true);

create policy "products_update_public"
on products for update
using (true)
with check (true);

create policy "products_delete_public"
on products for delete
using (true);

drop policy if exists "orders_insert_public" on orders;
drop policy if exists "orders_select_public" on orders;

create policy "orders_insert_public"
on orders for insert
with check (true);

create policy "orders_select_public"
on orders for select
using (true);

drop policy if exists "order_items_insert_public" on order_items;
drop policy if exists "order_items_select_public" on order_items;

create policy "order_items_insert_public"
on order_items for insert
with check (true);

create policy "order_items_select_public"
on order_items for select
using (true);

create index if not exists products_category_idx on products (category);
create index if not exists products_created_at_idx on products (created_at desc);
create index if not exists order_items_order_id_idx on order_items (order_id);

-- ═══════════════════════════════════════════
-- SEED DATA — 32 produits
-- ═══════════════════════════════════════════

-- Vide les tables avant d'insérer (pour pouvoir ré-exécuter ce script)
delete from order_items;
delete from orders;
delete from products;

insert into products (name, description, price, category, category_public, subcategory, image_url, discount_percent) values
-- ── Produits originaux du catalogue ──────────────────────────
(
  'SEBIACLEAR Hydra',
  'Hydrating soothing repair care, anti-marks long-lasting comfort.',
  115.000, 'FACE', 'Femmes', 'Soins hydratants et nourrissants',
  '/assets/hydratingSVR.webp', null
),
(
  'SVR Ampoule C Anti-Ox Concentrated Glow 30ml',
  'Ultra-concentrated serum with optimized vitamin C for a brighter complexion.',
  32.500, 'FACE', 'Femmes', 'Anti-âge & anti-rides',
  '/assets/VitaminC.avif', 15
),
(
  'AKTIV Omega 3 Marine 60 Capsules',
  'Helps maintain healthy cholesterol levels and contributes to cardiovascular health.',
  50.800, 'FOOD SUPPLEMENTS', null, 'Oméga & acides gras',
  '/assets/AKTIV.webp', null
),
(
  'Neutraderm Baby Detangling Shampoo Softness 200ml',
  'Soft shampoo adapted for baby hair and skin from birth.',
  28.500, 'BABY & MOM', 'Bébés (0-3 ans)', 'Bain & soins bébé',
  '/assets/prod4.webp', null
),
(
  'CLINO+ Hydroalcoholic Hand Gel 70% 500ml',
  'Hypoallergenic antiseptic preparation that effectively disinfects dry hands.',
  12.200, 'HYGIENE', null, 'Désinfectants mains',
  '/assets/prod5.webp', null
),
(
  'Nutrend EAA Mega Strong Powder 300g',
  'Nutrend EAA Mega Strong Powder instant blend of 9 essential amino acids enriched with vitamins, zinc and green tea.',
  139.000, 'FOOD SUPPLEMENTS', null, 'Protéines',
  '/assets/prod6.avif', null
),
(
  'Roncey Clairskin Hand Cream SPF 30+ 100ml',
  'Clairskin SPF30 hand cream with stabilized Vitamin C and Niacinamide — brightening and depigmenting treatment.',
  33.000, 'BODY', 'Femmes', 'Soins des mains',
  '/assets/prod7.avif', null
),
(
  'SVR Topialyse Cleansing Gel 200ml',
  'Cleanser designed for sensitive and dry skin. Suitable for face, body and hair.',
  22.750, 'BODY', 'Femmes', 'Hydratation & nutrition du corps',
  '/assets/prod8.avif', null
),
(
  'SVR Topialyse Cream 400ml',
  'Nourishing soothing cream for sensitive, dry, and uncomfortable skin. 48h effectiveness.',
  57.240, 'BODY', 'Femmes', 'Hydratation & nutrition du corps',
  '/assets/prod9.avif', null
),
(
  'ROGE CAVAILLES Special Dryness 250ml',
  'Intimate gel for women, enriched with prebiotics. Recommended by gynecologists.',
  26.200, 'BODY', 'Femmes', 'Hydratation & nutrition du corps',
  '/assets/prod10.avif', null
),
(
  'Chicco decorated flat and deep plate set for babies 12+ months, blue',
  'Set of 1 dinner plate and 1 soup plate with playful designs. Rims for resting a spoon or fork.',
  54.240, 'BABY & MOM', 'Bébés (0-3 ans)', 'Équipement bébé',
  '/assets/prod11.avif', null
),
(
  'Biolane Fresh Eau de Toilette 200ml',
  'Biolane Freshness Eau de Toilette — completes your baby''s bath time routine. Alcohol-free.',
  15.410, 'BABY & MOM', 'Bébés (0-3 ans)', 'Bain & soins bébé',
  '/assets/prod12.avif', null
),
(
  'Gum Ortho Soft Toothbrush 124',
  'Specialized toothbrush with v-shaped bristles for cleaning around orthodontic appliances.',
  11.650, 'HYGIENE', null, 'Hygiène intime',
  '/assets/prod13.webp', null
),

-- ── Bébés (0-3 ans) ──────────────────────────────────────────
(
  'Crème Hydratante Protectrice Biolane',
  'Soin doux hypoallergénique pour le corps et le visage de bébé, protège des rougeurs et de la sécheresse.',
  18.500, 'BABY & MOM', 'Bébés (0-3 ans)', 'Crèmes / soins',
  'https://images.unsplash.com/photo-1515488042361-404e9250afef?w=400&q=80', null
),
(
  'Biberon Anti-Colique Easy Active 270ml',
  'Tétine débit 2 ultra douce. Favorise une transition douce entre l''allaitement et le biberon.',
  24.900, 'BABY & MOM', 'Bébés (0-3 ans)', 'Cuillères / accessoires',
  'https://images.unsplash.com/photo-1555252333-9f8e92e65df9?w=400&q=80', null
),
(
  'Thermomètre Médical Pédiatrique Soft-Tip',
  'Thermomètre rectal et sous-axillaire à embout souple pour une mesure sûre et rapide.',
  29.900, 'BABY & MOM', 'Bébés (0-3 ans)', 'Matériel',
  'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=400&q=80', null
),
(
  'Body en Coton Biologique Lot de 3',
  'Manches longues, boutons pressions à l''entrejambe pour un change facile et un confort optimal.',
  35.000, 'BABY & MOM', 'Bébés (0-3 ans)', 'Vêtements',
  'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=400&q=80', null
),

-- ── Enfants (3-12 ans) ───────────────────────────────────────
(
  'Shampoing Démêlant Cerise & Amande Douce',
  'Ne pique pas les yeux. Formule biodégradable qui laisse les cheveux soyeux et parfumés.',
  14.800, 'HAIR', 'Enfants (3-12 ans)', 'Shampooings',
  'https://images.unsplash.com/photo-1535254973040-607b474cb50d?w=400&q=80', null
),
(
  'Gummies Multivitaminés Vitalité Kids',
  'Contient 12 vitamines et minéraux essentiels pour soutenir la croissance et l''énergie quotidienne.',
  32.000, 'FOOD SUPPLEMENTS', 'Enfants (3-12 ans)', 'Vitamines',
  'https://images.unsplash.com/photo-1628243382943-f11406126bb8?w=400&q=80', null
),
(
  'Baskets Légères Respirantes ActivePlay',
  'Fermeture scratch pratique pour l''école et le sport. Semelle antidérapante.',
  49.000, 'BABY & MOM', 'Enfants (3-12 ans)', 'Équipement bébé',
  'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&q=80', null
),

-- ── Femmes ────────────────────────────────────────────────────
(
  'Sérum Anti-Rides Concentré Acide Hyaluronique',
  'Repulpe la peau, lisse les ridules et procure une hydratation intense longue durée.',
  78.500, 'FACE', 'Femmes', 'Anti-âge & anti-rides',
  'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&q=80', null
),
(
  'Mascara Volumateur Bio Noir Intense',
  'Formule naturelle enrichie en huile de ricin pour renforcer et allonger les cils.',
  36.900, 'MAKEUP', 'Femmes', 'Yeux',
  'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400&q=80', null
),
(
  'Infusion Detox & Éclat aux Herbes Bio',
  'Mélange apaisant de menthe, romarin et pissenlit pour purifier l''organisme de l''intérieur.',
  19.500, 'DIETARY SUPPLEMENTS', 'Femmes', 'Antioxydants',
  'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=400&q=80', null
),
(
  'Huile de Massage Relaxante Lavande & Amande',
  'Détend les muscles et l''esprit après une longue journée. Parfum apaisant.',
  42.000, 'BODY', 'Femmes', 'Hydratation & nutrition du corps',
  'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=400&q=80', null
),

-- ── Hommes ────────────────────────────────────────────────────
(
  'Gel Hydratant Anti-Fatigue 24H',
  'Soin énergisant enrichi en magnésium et vitamine C pour combattre le teint terne et les cernes.',
  45.000, 'MEN', 'Hommes', 'Soins visage homme',
  'https://images.unsplash.com/photo-1617897903246-719242758050?w=400&q=80', null
),
(
  'Huile Barbe Adoucissante Bois de Cèdre',
  'Nourrit les poils en profondeur et hydrate la peau sous la barbe sans effet gras.',
  32.500, 'MEN', 'Hommes', 'Rasage & barbe',
  'https://images.unsplash.com/photo-1626015713026-d837d172406f?w=400&q=80', null
),
(
  'Gel Douche Purifiant 3-en-1 Charbon Actif',
  'Nettoie le visage, le corps et les cheveux. Élimine les impuretés, parfum boisé ultra frais.',
  16.900, 'BODY', 'Hommes', 'Hydratation & nutrition du corps',
  'https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?w=400&q=80', null
),

-- ── Personnes âgées ──────────────────────────────────────────
(
  'Baume Articulaire Fort Harpagophytum',
  'Soulage les raideurs articulaires et améliore la souplesse. Effet chauffant réconfortant.',
  39.900, 'BODY', 'Personnes âgées', 'Soins des articulations',
  'https://images.unsplash.com/photo-1550572017-edd951b55104?w=400&q=80', null
),
(
  'Tensiomètre de Bras Électronique Automatique',
  'Écran rétroéclairé, détection d''arythmie. Enregistrement des mesures pour 2 utilisateurs.',
  129.000, 'BODY', 'Personnes âgées', 'Soins du corps',
  'https://images.unsplash.com/photo-1603398938378-e54eab446dde?w=400&q=80', null
),
(
  'Chaussons Confort Ergonomiques Ajustables',
  'Chaussures d''intérieur extensibles adaptées aux pieds gonflés ou sensibles. Semelles antidérapantes.',
  59.000, 'BODY', 'Personnes âgées', 'Soins du corps',
  'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400&q=80', null
),
(
  'Complexe Magnésium Marin & Vitamine B6',
  'Soutient la fonction musculaire et nerveuse. Réduit la fatigue et régule le sommeil.',
  28.000, 'FOOD SUPPLEMENTS', 'Personnes âgées', 'Minéraux',
  'https://images.unsplash.com/photo-1616679911721-feb6e5e468b2?w=400&q=80', null
)

;
